### ISSUE TITLE
No longer can connect or discover hubs

### ISSUE THREAD

**Issue by github22222** [sushilks/harmonyHubCLI#16]
I had not used harmonyHubCli.js in a while when I found today that it no longer works. Of course I have no idea why. 

Connecting to hub at 192.168.1.116
errorhub { Error: connect ETIMEDOUT 192.168.1.116:5222
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.116',
  port: 5222 }

**Comment by github22222** [comment]
I found that it was a firewall thing on Windows 10. For some reason I had to allow Public access in addition to Private. This is strange to me but it works.
