### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by astanid** [sushilks/harmonyHubCLI#6]
Win 7 x64
I installed latest version from https://nodejs.org/en/
launched cmd.exe as admin and typed 'npm install'
i got lots of errors

`c:\Harmony\harmonyhubjs-client-master>npm install
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:63:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:72:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git+https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser resetting remote C:\Users\Astanid\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-swissmanu-ltx-git-cda
ta-for-ltx-parser-d923f26b because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Astanid\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/swissmanu/ltx.git C:\Users\Astanid\AppData\Roaming\npm-cache_git-remotes\g
it-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefined
npm ERR! git clone --template=C:\Users\Astanid\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/swissmanu/ltx.git C:\Users\Astanid\AppData\Roaming\npm-cache_git-remotes\g
it-https-github-com-swissmanu-ltx-git-cdata-for-ltx-parser-d923f26b: undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Harmony\harmonyhubjs-client-master\npm-debug.log

c:\Harmony\harmonyhubjs-client-master>`

what's the problem ? can you explain  in more detail what is need to lauch example js code

**Comment by sushilks** [comment]
I have not done much work on windows, however it appears that your installation is missing some other packages i.e. "git" seems to be missing. 
You will probably need to google around to find out the right way to install node on windows.

**Comment by destructure00** [comment]
If you install the github desktop client it will add a shortcut to a CLI that opens through Windows Powershell. Try using this instead of cmd.exe.

**Comment by sushilks** [comment]
@astanid  Are you still having problems ?

**Comment by sushilks** [comment]
No activity for a while. Let me know if it's still a problem.
